---
- name: Install Dependency Packages
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gpg
      - software-properties-common
    update_cache: true
    